spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: food
    password: tidlsl12
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 738597332863-9v725t82p9b57ub9q0e7rkffgc91fuc1.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          facebook:
            clientId: 1137332817214388
            clientSecret: e43529188e7116f86fcd198c4478526d
            scope:
              - email
              - public_profile
          Naver:
            clientId: sByVPiAnkUDzFdZJ_ShU
            clientSecret: fcw3yzQiTH
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver

        provider:
          Naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
    id: BFoDVJOn3hvD7PuDyR82
    secret: dRIlM0l6sE
